# Generated by Django 4.0.5 on 2022-07-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('log_id', models.IntegerField()),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
