# Generated by Django 4.0.5 on 2022-07-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_device_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='process',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
