# Generated by Django 4.0.5 on 2022-09-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_microcontroller_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
