# Generated by Django 4.0.5 on 2022-09-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_alert_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='physical_file',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
