# Generated by Django 4.0.5 on 2022-09-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_alert_physical_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='confidence',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=15),
        ),
    ]
